# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
env:
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: postgres://postgres:postgres@localhost:5432/expenses
  GOOSE_MIGRATION_DIR: ./migrations
  GOOSE_TABLE: goose.goose_migrations

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    cmds:
      - go run main.go
    env:
      GOTMPDIR: ".\\temp"

  tools:
    desc: install dev tools
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest

  goose:
    desc: handles any goose command, passed by as "taskfile goose -- <cmd>"
    cmds:
      - goose {{.CLI_ARGS}}
